function Temp_3HeInt = calcTemp_3HeInt(par,cryo,ind,Temp_3Helo,Temp_3Hehi)

Temp_3HeInt = Temp_3Helo +...
    (par.beamHeating + par.staticLoad - cryo.pumping.coolingPower(ind-1))./...
    (cryo.pumping.coolingPower(ind) - cryo.pumping.coolingPower(ind-1)).*...
    (Temp_3Hehi - Temp_3Helo);

end