function mu_aferirrad = calcmu_aferirrad(par,Vel_ncellAvg,F_prodvol,Surf_prod,Vol_prod,F_preHEXvol,Surf_preHEX,Vol_preHEX,F_HEXvol,Surf_HEX,Vol_HEX,F_postHEXvol,Surf_postHEX,Vol_postHEX,F_vapourVol,Surf_guidevapour,Vol_guidevapour,Vel_afterirradAvg)

mu_aferirrad = 4./par.T_wallinput./(Vel_ncellAvg.*...
    (F_prodvol.*Surf_prod./Vol_prod + F_preHEXvol.*Surf_preHEX./Vol_preHEX + ...
    F_HEXvol.*Surf_HEX./Vol_HEX + F_postHEXvol.*Surf_postHEX./Vol_postHEX) + ...
    F_vapourVol.*Surf_guidevapour./Vol_guidevapour.*Vel_afterirradAvg)./100;

end