function SVP = calcSVP(const)

SVP = exp(const.cryo.a./const.He.He3LatentHeatTable(:,1) + ...
    const.cryo.b.*log(const.He.He3LatentHeatTable(:,1)) + ...
    const.cryo.c + const.cryo.d.*const.He.He3LatentHeatTable(:,1) + ...
    const.cryo.e.*const.He.He3LatentHeatTable(:,1).^2 + ...
    const.cryo.f.*const.He.He3LatentHeatTable(:,1).^3 + ...
    const.cryo.g.*const.He.He3LatentHeatTable(:,1).^4)./100;

end